# When main branch is updated:
# - Build
# - Deploy the artifacts to Maven Central
# - Update the dependency graph
name: Maven Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    uses: metricshub/workflows/.github/workflows/maven-central-deploy.yml@v2
    with:
      jdkVersion: "17"
    secrets: inherit
