# This workflow releases the project on Maven Central
# and prepare a new development version

name: Release to Maven Central
run-name: Release v${{ inputs.releaseVersion }} to Maven Central

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true
        default: ""
      developmentVersion:
        description: "New SNAPSHOT version"
        required: true
        default: ""

jobs:
  release:
    uses: metricshub/workflows/.github/workflows/maven-central-release.yml@v2
    with:
      releaseVersion: ${{ inputs.releaseVersion }}
      developmentVersion: ${{ inputs.developmentVersion }}
      autoRelease: false
      jdkVersion: "17"
    secrets: inherit
